export const images = {
  logo: require('../assets/images/logo.png'),
  Adherence: require('../assets/images/adherenece.png'),
  googleIcon: require('../assets/images/google-icon.png'),
  chartBeat: require('../assets/images/chartbeat.png'),
  starsWhite: require('../assets/images/stars-white.png'),
  stars: require('../assets/images/stars.png'),
  brain: require('../assets/images/brain.png'),
  brainPurpleIcon: require('../assets/images/brain-purple.png'),
  brainPrimary: require('../assets/images/brain-primary.png'),
  brainDark: require('../assets/images/brain-dark.png'),
  homeIcon: require('../assets/images/home-icon.png'),
  profileIcon: require('../assets/images/profile-icon.png'),
  aiIcon: require('../assets/images/ai-icon.png'),
};
